import type { Metadata } from "next";
import "./globals.css";
import Testimonial from "@/components/testimonial";
import BookingProcess from "@/components/booking";
import PriceSection from "@/components/prices";

export const metadata: Metadata = {
  title: "루이스키",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`antialiased relative`}>
        {children}
        <Testimonial />
        <BookingProcess />
        <PriceSection />
      </body>
    </html>
  );
}
